version: '2.1'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
      - "8080:8080"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_LOG4J_PROP: "WARN,ROLLINGFILE"
    volumes:
      - ./volumes/zoo1/data:/data
      - ./volumes/zoo1/datalog:/datalog

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP}:9092
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,state.change.logger=WARN"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/kafka1/data:/var/lib/kafka/data
      - ./volumes/kafka/logs:/tmp/kafka-logs
      - ./volumes/kafka1/logs:/kafka/kafka-logs-kafka1
    depends_on:
      - zoo1

  scan-generator1:
    image: corourke/scan_generator
    hostname: scan_generator1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092"
      PRODUCER_INSTANCE: "01"
    depends_on:
      - kafka1
